"""
EdgeShield Shared Models
"""
from .enums import (
    DeviceType,
    DeviceStatus,
    IncidentSeverity,
    IncidentStatus,
    RemediationActionType,
    ApprovalStatus,
    UserRole,
    AuditAction,
)
from .device import Device, Gateway, TopicPermission, FirmwareRecord
from .telemetry import (
    RawTelemetry,
    NormalizedTelemetry,
    SensorMeasurement,
    TelemetryValidationResult,
)
from .detection import DetectionRule, DetectorResult, BaselineMetric
from .incident import (
    Incident,
    EvidenceItem,
    Citation,
    RiskAssessment,
    RecommendedActionProposal,
)
from .remediation import RemediationProposal, Approval, ApprovalRequest
from .audit import AuditEvent
from .auth import User, UserPublic, Token, TokenPayload, LoginRequest
from .mcp_schemas import (
    GetDeviceProfileInput,
    GetDeviceProfileOutput,
    QueryRecentTelemetryInput,
    QueryRecentTelemetryOutput,
    CompareBehaviorBaselineInput,
    CompareBehaviorBaselineOutput,
    InspectMqttPermissionsInput,
    InspectMqttPermissionsOutput,
    CheckFirmwareRiskInput,
    CheckFirmwareRiskOutput,
    CreateIncidentReportInput,
    CreateIncidentReportOutput,
    ProposeSafeRemediationInput,
    ProposeSafeRemediationOutput,
    GetAuditEventsInput,
    GetAuditEventsOutput,
)

__all__ = [
    "DeviceType",
    "DeviceStatus",
    "IncidentSeverity",
    "IncidentStatus",
    "RemediationActionType",
    "ApprovalStatus",
    "UserRole",
    "AuditAction",
    "Device",
    "Gateway",
    "TopicPermission",
    "FirmwareRecord",
    "RawTelemetry",
    "NormalizedTelemetry",
    "SensorMeasurement",
    "TelemetryValidationResult",
    "DetectionRule",
    "DetectorResult",
    "BaselineMetric",
    "Incident",
    "EvidenceItem",
    "Citation",
    "RiskAssessment",
    "RecommendedActionProposal",
    "RemediationProposal",
    "Approval",
    "ApprovalRequest",
    "AuditEvent",
    "User",
    "UserPublic",
    "Token",
    "TokenPayload",
    "LoginRequest",
    "GetDeviceProfileInput",
    "GetDeviceProfileOutput",
    "QueryRecentTelemetryInput",
    "QueryRecentTelemetryOutput",
    "CompareBehaviorBaselineInput",
    "CompareBehaviorBaselineOutput",
    "InspectMqttPermissionsInput",
    "InspectMqttPermissionsOutput",
    "CheckFirmwareRiskInput",
    "CheckFirmwareRiskOutput",
    "CreateIncidentReportInput",
    "CreateIncidentReportOutput",
    "ProposeSafeRemediationInput",
    "ProposeSafeRemediationOutput",
    "GetAuditEventsInput",
    "GetAuditEventsOutput",
]
